### ISSUE TITLE
errorhandling

### ISSUE THREAD

**Issue by Aslan0** [entropybit/slaprinter#12]
all input fields can be sabotaged by i.e. putting "hase" as a printing volume height value. this is not DAU-friendly. and they're studying biology after all...

**Comment by entropybit** [comment]
For this a user input evaluation should be done before accepting the input. This seems to be exactly what we need to do this in python: 

http://snorf.net/blog/2014/08/09/using-qvalidator-in-pyqt4-to-validate-user-input/
