### ISSUE TITLE
OpenGL: display of .stl

### ISSUE THREAD

**Issue by Aslan0** [entropybit/slaprinter#5]
The .stl needs to be displayed in both printing windows

**Comment by entropybit** [comment]
Btw I thought to use this to get an easily accesible STL file model for displaying and slicing
https://github.com/WoLpH/numpy-stl

**Comment by entropybit** [comment]
This has been solved by using numpy-stl and defining an according model and a model view for displaying with opengl

It was important that display lists are used instead of "normal" rendering since this gets slow really fast ...
