### ISSUE TITLE
Deamon @ raspberry

### ISSUE THREAD

**Issue by Aslan0** [entropybit/slaprinter#8]
Has to listen to: start/pause/stop signal

Has to receive/check if its there:
1. .stl (for preview),
2. slice-stack
3. .conf-file

Should log connections made with timestamp and ip and pc name

**Comment by Aslan0** [comment]
also should send current status of printing incl .stl , slice-stack and slice-number back to any client that connects to it.

**Comment by entropybit** [comment]
We most likely will solve this by some combination of a linux init.d script and some command line functionality implemented within the sla_printer software.

However this is one of the last features to implement ^^

**Comment by entropybit** [comment]
In principal this functionaliyt is implemented the only missing parts are maybe a more advanced logging the other functionality is / will be handled by the web interface
